function var_area_modal_carga (nombre) {
  var modal_html = '<div id="'+nombre+'" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="area_modalLabel" aria-hidden="true"><div class="modal-header"><button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button><h3 id="area_modalLabel">Procesando <img src="http://funsepa.net/suni/js/framework/select2/select2-spinner.gif"></h3></div><div class="modal-body"><p>Por favor espere...</p></div></div>';
  return modal_html;
}
function var_formulario_excel (nombre) {
  var formulario_excel = '<form class="form-inline well" method="post" target="_blank" id="'+nombre+'"><input type="hidden" id="datos_excel" name="datos_excel" /></form>';
  return formulario_excel;
}
function var_formulario_excel_correo (nombre) {
  var formulario_excel = '<form class="form-horizontal"><fieldset><div class="control-group"><label class="control-label" for="mail_para">Para</label><div class="controls"><input id="mail_para" name="mail_para" placeholder="" class="input-large" required="" ype="text"></div></div><div class="control-group"><label class="control-label" for="mail_asunto">Asunto</label><div class="controls"><input id="mail_asunto" name="mail_asunto" placeholder="" class="input-large" required="" ype="text"></div></div><div class="control-group"><label class="control-label" for="mail_body">Mensaje</label><div class="controls">                     <textarea id="mail_body" name="mail_body"></textarea></div></div></fieldset></form>';
  return formulario_excel;
}
function var_formulario_nuevo_gn_contacto (nombre, lista_tag, lista_emp, lista_evn) {
  var formulario_nuevo_gn_contacto = '<form class="hide" id="h_nuevo_contacto">'+'<table class="table table-bordered table-striped">'+'<tbody> '+'<tr>         '+'<td width="30%">Nombre</td>'+'<td><input type="text" id="nombre_contacto" name="nombre_contacto" data-type="text" data-name="nombre" data-original-title="Enter username" required></input></td>'+'</tr>'+'<tr>         '+'<td width="30%">Apellido</td>'+'<td><input type="text" id="apellido_contacto" name="apellido_contacto" data-type="text" data-name="apellido" data-original-title="Enter username" required></input></td>'+'</tr>'+'<tr>         '+'<td width="30%">E-mail</td>'+'<td><input type="email" id="mail_contacto" name="mail_contacto" required></input><a id="a_val_mail" href="#" data-toggle="tooltip" title="El correo está disponible"><i id="i_val_mail" class=""></i> </a></td>'+'</tr>'+'<tr>'+'<td width="30%">Etiqueta</td>'+'<td>'+'<select name="etiqueta_contacto" id="etiqueta_contacto">'+lista_tag+'</select>'+'</td>'+'</tr>'+'<tr>'+'<td width="30%">Evento</td>'+'<td>'+'<select name="evento_contacto" id="evento_contacto">'+lista_evn+'</select> <a href="#" class="label label-info" id="mostrar_nueva_evn">+</a>'+'</td>'+'</tr>'+'<tr>'+'<td width="30%">Género</td>'+'<td>'+'<select name="genero_contacto" id="genero_contacto">'+'<option value="1">Hombre</option>'+'<option value="2">Mujer</option>'+'</select>'+'</td>'+'</tr>'+'<tr>'+'<td width="30%">Empresa</td>'+'<td>'+'<select name="empresa_contacto" id="empresa_contacto">'+lista_emp+'</select> <a href="#" class="label label-info" id="mostrar_nueva_emp">+</a>'+'</td>'+'</tr>'+'<tr>         '+'<td width="30%">Dirección</td>'+'<td><input type="text" id="direccion_contacto" name="direccion_contacto"></input></td>'+'</tr>'+'<tr>         '+'<td width="30%">Teléfono fijo</td>'+'<td><input type="text" id="tel_casa_contacto" name="tel_casa_contacto"></input></td>'+'</tr>'+'<tr>         '+'<td width="30%">Teléfono móvil</td>'+'<td><input type="text" id="tel_movil_contacto" name="tel_movil_contacto"></input></td>'+'</tr>'+'<tr>         '+'<td>Fecha de nacimiento</td>'+'<td><input type="text" id="fecha_nac_contacto" name="fecha_nac_contacto"></input></td>'+'</tr>  '+'<tr>         '+'<td>Observaciones</td>'+'<td><input type="text" id="observaciones_contacto" name="observaciones_contacto"></input></td>'+'</tr> '+'</tbody>'+'</table><br><button class="btn" onclick="cerrar_nuevo_contacto(); return false" id="btn_cancelar_nuevo">Cancelar</button><button class="btn btn-primary" id="btn_crear_nuevo" >Guardar</button>'+'</form>';
  return formulario_nuevo_gn_contacto;
}
function var_tabla_contacto (nombre) {
  var tabla_contacto =
  "<table  class='table table-bordered' id='t_contactos'>"+"<thead>"+"<th>Nombre</th>"+"<th>Apellido</th>"+"<th>Correo</th>"+"<th>Teléfono</th><th>Empresa</th>"+"</thead>"+"<tbody id='tbody_contactos'></tbody>"+"</table>"+"<button class='btn btn-success' onclick='descargar_tabla_excel(\"t_contactos\");'><i class='icon-download-alt'></i></button>"+" <button class='btn btn-info' onclick='descargar_tabla_excel(\"t_contactos\",\"dir_mail_excel\");'><i class='icon-envelope-alt'></i></button>";
  return tabla_contacto;
}